# Copyright 2025 Perfana Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- _id: gatling-profile
  name: gatling
  description: Profile for Gatling load test tool dashboards and metrics
  tags:
    - gatling
  readOnly: true
- _id: k6-profile
  name: k6
  description: Profile for K6 load test tool dashboards and metrics
  tags:
    - k6
  readOnly: true
- _id: jmeter-profile
  name: jmeter
  description: Profile for Jmeter load test tool dashboards and metrics
  tags:
    - jmeter
  readOnly: true
- _id: neoload-profile
  name: neoload
  description: Profile for neoload load test tool dashboards and metrics
  tags:
    - neoload
  readOnly: true
- _id: jfr-profile
  name: jfr
  description: Profile for jfr dashboard and metrics
  tags:
    - jfr
  readOnly: true
- _id: spring-boot-kubernetes-profile
  name: spring-boot-kubernetes
  description: Profile for Spring Boot application dashboards and metrics
  tags:
    - spring-boot-kubernetes
  readOnly: true
- _id: kubernetes
  name: kubernetes
  description: Profile for Kubernetes dashboards and metrics
  tags:
    - kubernetes
  readOnly: true
- _id: spanmetrics
  name: spanmetrics
  description: Profile for span metrics
  tags:
    - spanmetrics
  readOnly: true  
- _id: docker
  name: docker
  description: Profile for docker metrics
  tags:
    - docker
  readOnly: true  