# Copyright 2025 Perfana Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build perfana-fe snapshot image

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:

jobs:
  build_snapshot_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from code branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install git-tag-version
        run: |
          sudo npm install -g git-tag-version
      - name: Get tag
        run: |
          echo 'TAG_NAME<<EOF' >> $GITHUB_ENV
          git-tag-version >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: set tag name with short sha
        run: echo "VERSION_TAG=${{ env.TAG_NAME }}-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Write tag to file
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "version.txt"
          FILE_DATA: "${{ env.VERSION_TAG }}"
      - name: Upload versions.txt to use in performance-test job
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.txt
#      - name: Run Snyk to check for vulnerabilities
 #       uses: snyk/actions/node@master
 #       env:
 #         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 #       with:
 #         args: --severity-threshold=high
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Build the tagged Docker image
        run: |
          echo ${{ env.TAG_NAME }}
          docker buildx build --platform linux/amd64,linux/arm64 --push --build-arg NODE_VERSION=14.21.4  -t perfana/perfana-fe-test:${{ env.VERSION_TAG }} .
          
#      - name: Run Snyk to check Docker image for vulnerabilities
#        continue-on-error: false
#        uses: snyk/actions/docker@master
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#        with:
#          image: perfana/perfana-fe-test:${{ env.VERSION_TAG }}
#          args: --severity-threshold=high --app-vulns
#      - name: Push the tagged Docker image
#        run: docker push perfana/perfana-fe-test:${{ env.VERSION_TAG }}

      ## checkout perfana-gitops
      - name: Checkout perfana-gitops
        uses: actions/checkout@v4
        with:
          repository: perfana/perfana-gitops
          token: ${{ secrets.PAT }}
          path: perfana-gitops
      - name: Replace image snapshot
        working-directory: perfana-gitops
        run: |
          repository="repository: perfana/perfana-fe-test"
          tag="tag: ${{ env.VERSION_TAG }}"
          echo "$repository"
          echo "$tag"
          ls -all
          sed -i "s|repository: .*|$repository|g" ./apps/perfana/test/perfana/perfana-fe-values.yaml
          sed -i "s|tag: .*|$tag|g" ./apps/perfana/test/perfana/perfana-fe-values.yaml
      - name: Commit files
        working-directory: perfana-gitops
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Bumped perfana-fe-test to ${{ env.VERSION_TAG }} in demo environment" -a
          git push
